### ISSUE TITLE
API에 대한 Swagger 추가 설정

### ISSUE THREAD

**Issue by i-Veni-Vidi-Vici** [AI-Team-02/hero-factoey-service#35]
# 🌈 Success criteria

# 👷To-do
- [x] 게임 오브젝트 API Swagger 설정
- [x] 로그인 API Swagger 설정
- [x] 로그인이 필요한 API Swagger 설정

# 👓 Review
1. <작업진행 상황을 스크린샷등 각종 이미지등으로 적극적으로 작성하고, 코드리뷰때 전달합니다.>
